#!/bin/bash
set -uo pipefail

ROOTLABEL="shani_root"
SCRIPT_VERSION="3"

log() { echo "$(date "+%Y-%m-%d %H:%M:%S") [beesd-setup] $*"; }

if [[ ! -e "/dev/disk/by-label/${ROOTLABEL}" ]] && [[ ! -e "/dev/mapper/${ROOTLABEL}" ]]; then
    log "WARN: Device not found — both by-label and mapper missing."
    exit 0
fi

UUID=$(findmnt -no UUID / 2>/dev/null | tr -d '[:space:]' || true)
if [[ -z "$UUID" ]]; then
    UUID=$(blkid -s UUID -o value /dev/disk/by-label/"${ROOTLABEL}" 2>/dev/null || true)
fi
if [[ -z "$UUID" ]] && [[ -e "/dev/mapper/${ROOTLABEL}" ]]; then
    UUID=$(blkid -s UUID -o value /dev/mapper/"${ROOTLABEL}" 2>/dev/null || true)
fi
if [[ -z "$UUID" ]]; then
    log "WARN: Could not resolve BTRFS UUID for ${ROOTLABEL}."
    exit 0
fi

CONF="/etc/bees/${UUID}.conf"
SERVICE="beesd@${UUID}.service"

if [[ -f "$CONF" ]] \
    && grep -q "^# version=${SCRIPT_VERSION}$" "$CONF" 2>/dev/null \
    && systemctl is-enabled --quiet "$SERVICE" 2>/dev/null; then
    log "Already configured (version=${SCRIPT_VERSION}), skipping."
    exit 0
fi

if [[ -e "/dev/mapper/${ROOTLABEL}" ]]; then
    BTRFS_DEV="/dev/mapper/${ROOTLABEL}"
elif [[ -e "/dev/disk/by-uuid/${UUID}" ]]; then
    BTRFS_DEV="/dev/disk/by-uuid/${UUID}"
else
    BTRFS_DEV="/dev/disk/by-label/${ROOTLABEL}"
fi

log "Writing ${CONF} (UUID=${UUID}, device=${BTRFS_DEV})"
mkdir -p /etc/bees || { log "WARN: cannot create /etc/bees — bees deduplication will not be configured"; exit 0; }

# Evaluate sizing HERE, at generation time. This file is consumed by
# systemd as an EnvironmentFile (beesd@.service), which performs no
# command substitution or arithmetic — writing '$((...))' into the conf
# would leave DB_SIZE as a literal string that bees cannot parse.
FS_BYTES=$(lsblk -b -no SIZE "${BTRFS_DEV}" 2>/dev/null | head -1 | tr -d '[:space:]')
case ${FS_BYTES:-0} in
    ''|*[!0-9]*) FS_BYTES=0 ;;
esac

_FS_TB=$(( (FS_BYTES + 500000000000) / 1000000000000 ))
if (( _FS_TB < 1 )); then _FS_TB=1; fi
if (( _FS_TB > 4 )); then _FS_TB=4; fi
DB_SIZE=$(( _FS_TB * 256 * 1024 * 1024 ))

# Idle tuning: --throttle-factor 2.0 doubles the idle time between ops
# vs the old 1.0, and --loadavg-target (evaluated here, per-machine)
# makes bees shed worker threads whenever system load exceeds core
# count, so dedup yields to interactive use and deploy bursts instead
# of compounding them. Slower convergence is the accepted tradeoff.
_THROTTLE="2.0"
_LOAD_TARGET=$(nproc 2>/dev/null || echo 4)
case ${_LOAD_TARGET:-0} in
    ''|*[!0-9]*) _LOAD_TARGET=4 ;;
esac
if (( _LOAD_TARGET < 1 )); then _LOAD_TARGET=1; fi

cat > "$CONF" <<CONF
# /etc/bees/${UUID}.conf
# Generated by beesd-setup.sh — do not edit manually.
# version=${SCRIPT_VERSION}
UUID=${UUID}
DB_SIZE=${DB_SIZE}

OPTIONS="--strip-paths --no-timestamps --throttle-factor ${_THROTTLE} --loadavg-target ${_LOAD_TARGET}"
CONF

if ! systemctl is-enabled --quiet "$SERVICE" 2>/dev/null; then
    log "Enabling ${SERVICE}"
    systemctl enable "$SERVICE" 2>/dev/null || log "WARN: could not enable ${SERVICE}"
fi

log "Done — UUID=${UUID}"
